name: Update VIP Playlist
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run Script
        run: |
          cd vipsports/
          node alpha_live.js
          if [ -f "live.m3u" ]; then mv live.m3u ../live.m3u; fi
      - name: Push
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Combined-Bot"
          git add live.m3u
          git commit -m "Update Playlist $(date)" || exit 0
          git push
