name: Auto Scanner

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动运行一次
  workflow_dispatch:      # 支持手动点击按钮运行

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 关键：必须有写入权限
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install aiohttp

      - name: Run Scanner
        run: |
          python scan/scanner.py
          ls -lh scan/

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          touch scan/useful_proxies.txt
          git add scan/useful_proxies.txt
          git commit -m "自动更新扫描结果 [$(date)]" || exit 0
          git push --force origin main   # 改为强制推送
