name: UDP IPTV 自动扫描追加

on:
  workflow_dispatch:      # 手动触发
  schedule:
    - cron: '0 22 * * *'  # 每天凌晨 6 点(北京时间)自动跑一次

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 赋予写入权限，这一步非常重要

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          pip install aiohttp

      - name: 运行扫描脚本
        run: python scan/udp.py

      - name: 提交并推送结果
        run: |
          git config --local user.email "github-actions[bot]@://github.com"
          git config --local user.name "github-actions[bot]"
          # 检查是否有文件更新，如果有则提交
          git add *.txt
          if git diff --staged --quiet; then
            echo "没有发现新 IP，跳过提交。"
          else
            git commit -m "自动更新: 新增有效直播源 [$(date '+%Y-%m-%d %H:%M')]"
            git push
          fi
